#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : watchdogd
Version  : 3.3
Release  : 5
URL      : https://github.com/troglobit/watchdogd/releases/download/3.3/watchdogd-3.3.tar.xz
Source0  : https://github.com/troglobit/watchdogd/releases/download/3.3/watchdogd-3.3.tar.xz
Summary  : Watchdog daemon with process supervisor/instrumentation API
Group    : Development/Tools
License  : ISC
Requires: watchdogd-bin = %{version}-%{release}
Requires: watchdogd-data = %{version}-%{release}
Requires: watchdogd-lib = %{version}-%{release}
Requires: watchdogd-license = %{version}-%{release}
Requires: watchdogd-man = %{version}-%{release}
Requires: watchdogd-services = %{version}-%{release}
BuildRequires : pkgconfig(libconfuse)
BuildRequires : pkgconfig(libite)
BuildRequires : pkgconfig(libuev)
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev

%description
System & Process Supervisor for Linux
=====================================
[![License Badge][]][License] [![Travis Status][]][Travis] [![Coverity Status][]][Coverity Scan]

%package bin
Summary: bin components for the watchdogd package.
Group: Binaries
Requires: watchdogd-data = %{version}-%{release}
Requires: watchdogd-license = %{version}-%{release}
Requires: watchdogd-services = %{version}-%{release}

%description bin
bin components for the watchdogd package.


%package data
Summary: data components for the watchdogd package.
Group: Data

%description data
data components for the watchdogd package.


%package dev
Summary: dev components for the watchdogd package.
Group: Development
Requires: watchdogd-lib = %{version}-%{release}
Requires: watchdogd-bin = %{version}-%{release}
Requires: watchdogd-data = %{version}-%{release}
Provides: watchdogd-devel = %{version}-%{release}
Requires: watchdogd = %{version}-%{release}
Requires: watchdogd = %{version}-%{release}

%description dev
dev components for the watchdogd package.


%package doc
Summary: doc components for the watchdogd package.
Group: Documentation
Requires: watchdogd-man = %{version}-%{release}

%description doc
doc components for the watchdogd package.


%package lib
Summary: lib components for the watchdogd package.
Group: Libraries
Requires: watchdogd-data = %{version}-%{release}
Requires: watchdogd-license = %{version}-%{release}

%description lib
lib components for the watchdogd package.


%package license
Summary: license components for the watchdogd package.
Group: Default

%description license
license components for the watchdogd package.


%package man
Summary: man components for the watchdogd package.
Group: Default

%description man
man components for the watchdogd package.


%package services
Summary: services components for the watchdogd package.
Group: Systemd services

%description services
services components for the watchdogd package.


%prep
%setup -q -n watchdogd-3.3
cd %{_builddir}/watchdogd-3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578326753
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1578326753
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/watchdogd
cp %{_builddir}/watchdogd-3.3/LICENSE %{buildroot}/usr/share/package-licenses/watchdogd/87a19066dc7e073dbd15c37d216bbd4c90c4c08f
%make_install
## install_append content
install -D -m 00644 watchdogd.conf %{buildroot}/usr/share/defaults/watchdogd/watchdogd.conf
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/watchdogctl
/usr/bin/watchdogd

%files data
%defattr(-,root,root,-)
/usr/share/defaults/watchdogd/watchdogd.conf

%files dev
%defattr(-,root,root,-)
/usr/include/wdog/compat.h
/usr/include/wdog/wdog.h
/usr/lib64/libwdog.so
/usr/lib64/pkgconfig/libwdog.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/watchdogd/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwdog.so.1
/usr/lib64/libwdog.so.1.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/watchdogd/87a19066dc7e073dbd15c37d216bbd4c90c4c08f

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/watchdogctl.1
/usr/share/man/man5/watchdogd.conf.5
/usr/share/man/man8/watchdogd.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/watchdogd.service
