#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : watchdogd
Version  : 3.1
Release  : 1
URL      : https://github.com/troglobit/watchdogd/releases/download/3.1/watchdogd-3.1.tar.xz
Source0  : https://github.com/troglobit/watchdogd/releases/download/3.1/watchdogd-3.1.tar.xz
Summary  : Watchdog daemon with process supervisor/instrumentation API
Group    : Development/Tools
License  : ISC
Requires: watchdogd-bin
Requires: watchdogd-lib
Requires: watchdogd-license
Requires: watchdogd-man
Requires: watchdogd-config
BuildRequires : pkgconfig(libconfuse)
BuildRequires : pkgconfig(libite)
BuildRequires : pkgconfig(libuev)
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev

%description
System & Process Supervisor for Linux
=====================================
[![License Badge][]][License] [![Travis Status][]][Travis] [![Coverity Status][]][Coverity Scan]

%package bin
Summary: bin components for the watchdogd package.
Group: Binaries
Requires: watchdogd-config = %{version}-%{release}
Requires: watchdogd-license = %{version}-%{release}
Requires: watchdogd-man = %{version}-%{release}

%description bin
bin components for the watchdogd package.


%package config
Summary: config components for the watchdogd package.
Group: Default

%description config
config components for the watchdogd package.


%package dev
Summary: dev components for the watchdogd package.
Group: Development
Requires: watchdogd-lib = %{version}-%{release}
Requires: watchdogd-bin = %{version}-%{release}
Provides: watchdogd-devel = %{version}-%{release}

%description dev
dev components for the watchdogd package.


%package doc
Summary: doc components for the watchdogd package.
Group: Documentation
Requires: watchdogd-man = %{version}-%{release}

%description doc
doc components for the watchdogd package.


%package lib
Summary: lib components for the watchdogd package.
Group: Libraries
Requires: watchdogd-license = %{version}-%{release}

%description lib
lib components for the watchdogd package.


%package license
Summary: license components for the watchdogd package.
Group: Default

%description license
license components for the watchdogd package.


%package man
Summary: man components for the watchdogd package.
Group: Default

%description man
man components for the watchdogd package.


%prep
%setup -q -n watchdogd-3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537475893
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1537475893
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/watchdogd
cp LICENSE %{buildroot}/usr/share/doc/watchdogd/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/watchdogctl
/usr/bin/watchdogd

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/watchdogd.service

%files dev
%defattr(-,root,root,-)
/usr/include/wdog/compat.h
/usr/include/wdog/wdog.h
/usr/lib64/libwdog.so
/usr/lib64/pkgconfig/libwdog.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/watchdogd/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwdog.so.1
/usr/lib64/libwdog.so.1.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/watchdogd/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/watchdogctl.1
/usr/share/man/man5/watchdogd.conf.5
/usr/share/man/man8/watchdogd.8
